[build]
  command = "npm install && npm run build -- --configuration production"
  publish = "dist"

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true

# Catch-all rule for Angular routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
